/*
 * Mailer service API
 * Mailer service for microservices architecture for sending emails.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lazydev.stksongbook.mailer.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lazydev.stksongbook.mailer.client.model.ApiHealthMailerHealth;
import com.lazydev.stksongbook.mailer.client.model.ApiHealthMongoHealth;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * API&#39;s health
 */
@ApiModel(description = "API's health")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-25T00:05:28.841+02:00")
public class ApiHealth {
  @JsonProperty("active")
  private String active = null;

  @JsonProperty("version")
  private String version = null;

  @JsonProperty("application_name")
  private String applicationName = null;

  @JsonProperty("mailer_health")
  private ApiHealthMailerHealth mailerHealth = null;

  @JsonProperty("mongo_health")
  private ApiHealthMongoHealth mongoHealth = null;

  public ApiHealth active(String active) {
    this.active = active;
    return this;
  }

   /**
   * Indicates if the server is active
   * @return active
  **/
  @ApiModelProperty(value = "Indicates if the server is active")
  public String getActive() {
    return active;
  }

  public void setActive(String active) {
    this.active = active;
  }

  public ApiHealth version(String version) {
    this.version = version;
    return this;
  }

   /**
   * API version
   * @return version
  **/
  @ApiModelProperty(value = "API version")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public ApiHealth applicationName(String applicationName) {
    this.applicationName = applicationName;
    return this;
  }

   /**
   * Get applicationName
   * @return applicationName
  **/
  @ApiModelProperty(value = "")
  public String getApplicationName() {
    return applicationName;
  }

  public void setApplicationName(String applicationName) {
    this.applicationName = applicationName;
  }

  public ApiHealth mailerHealth(ApiHealthMailerHealth mailerHealth) {
    this.mailerHealth = mailerHealth;
    return this;
  }

   /**
   * Get mailerHealth
   * @return mailerHealth
  **/
  @ApiModelProperty(value = "")
  public ApiHealthMailerHealth getMailerHealth() {
    return mailerHealth;
  }

  public void setMailerHealth(ApiHealthMailerHealth mailerHealth) {
    this.mailerHealth = mailerHealth;
  }

  public ApiHealth mongoHealth(ApiHealthMongoHealth mongoHealth) {
    this.mongoHealth = mongoHealth;
    return this;
  }

   /**
   * Get mongoHealth
   * @return mongoHealth
  **/
  @ApiModelProperty(value = "")
  public ApiHealthMongoHealth getMongoHealth() {
    return mongoHealth;
  }

  public void setMongoHealth(ApiHealthMongoHealth mongoHealth) {
    this.mongoHealth = mongoHealth;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiHealth apiHealth = (ApiHealth) o;
    return Objects.equals(this.active, apiHealth.active) &&
        Objects.equals(this.version, apiHealth.version) &&
        Objects.equals(this.applicationName, apiHealth.applicationName) &&
        Objects.equals(this.mailerHealth, apiHealth.mailerHealth) &&
        Objects.equals(this.mongoHealth, apiHealth.mongoHealth);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, version, applicationName, mailerHealth, mongoHealth);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiHealth {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    applicationName: ").append(toIndentedString(applicationName)).append("\n");
    sb.append("    mailerHealth: ").append(toIndentedString(mailerHealth)).append("\n");
    sb.append("    mongoHealth: ").append(toIndentedString(mongoHealth)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

